# Generated by Django 6.0.5 on 2026-06-29 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KotlowniaFormularz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('godzina', models.TimeField(verbose_name='Godzina')),
                ('podpis_techniczny', models.CharField(blank=True, max_length=200, verbose_name='Czytelny podpis (Dział Techniczny)')),
                ('woda_socjalna_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Woda miejska - Pomieszczenie socjalne [m3]')),
                ('woda_produkcja_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Woda miejska - Produkcja [m3]')),
                ('olej_poziom_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Olej opałowy - Poziom zbiornika [cm]')),
                ('olej_licznik_litry', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Olej opałowy - Licznik oleju [litry]')),
                ('gaz_cisnienie_1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Gaz zbiornik 1 - Ciśnienie [bar]')),
                ('gaz_wypelnienie_1', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Gaz zbiornik 1 - Wypełnienie [%]')),
                ('gaz_cisnienie_2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gaz_wypelnienie_2', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('gaz_cisnienie_3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gaz_wypelnienie_3', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('gaz_cisnienie_4', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gaz_wypelnienie_4', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('gaz_cisnienie_5', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gaz_wypelnienie_5', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('gaz_cisnienie_6', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gaz_wypelnienie_6', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('b1_wartosc', models.CharField(blank=True, max_length=100, verbose_name='1. Wskaźnik poziomu wody - Wartość')),
                ('b1_uwagi', models.TextField(blank=True, verbose_name='1. Wskaźnik poziomu wody - Uwagi')),
                ('b2_wartosc', models.CharField(blank=True, max_length=100, verbose_name='2. Regulator poziomu wody - Wartość')),
                ('b2_uwagi', models.TextField(blank=True)),
                ('b3_wartosc', models.CharField(blank=True, max_length=100, verbose_name='3. Regulator temperatury lub ciśnienia - Wartość')),
                ('b3_uwagi', models.TextField(blank=True)),
                ('b4_wartosc', models.CharField(blank=True, max_length=100, verbose_name='4. Urządzenie do opróżniania lub odsalania kotła - Wartość')),
                ('b4_uwagi', models.TextField(blank=True)),
                ('b5_wartosc', models.CharField(blank=True, max_length=100, verbose_name='5. Aparatura kontroli zanieczyszczeń - Wartość')),
                ('b5_uwagi', models.TextField(blank=True)),
                ('b6_wartosc', models.CharField(blank=True, max_length=100, verbose_name='6. Regulacja palnika - Wartość')),
                ('b6_uwagi', models.TextField(blank=True)),
                ('b7_wartosc', models.CharField(blank=True, max_length=100, verbose_name='7. Wentylatory - Wartość')),
                ('b7_uwagi', models.TextField(blank=True)),
                ('b8_wartosc', models.CharField(blank=True, max_length=100, verbose_name='8. Awaryjne urządzenie odcinające - Wartość')),
                ('b8_uwagi', models.TextField(blank=True)),
                ('b9_wartosc', models.CharField(blank=True, max_length=100, verbose_name='9. Zapłon - Wartość')),
                ('b9_uwagi', models.TextField(blank=True)),
                ('b10_wartosc', models.CharField(blank=True, max_length=100, verbose_name='10. Wentylacja - Wartość')),
                ('b10_uwagi', models.TextField(blank=True)),
                ('b11_wartosc', models.CharField(blank=True, max_length=100, verbose_name='11. Kontrola płomienia - Wartość')),
                ('b11_uwagi', models.TextField(blank=True)),
                ('b12_wartosc', models.CharField(blank=True, max_length=100, verbose_name='12. Ocena jakości spalania - Wartość')),
                ('b12_uwagi', models.TextField(blank=True)),
                ('b13_wartosc', models.CharField(blank=True, max_length=100, verbose_name='13. Licznik - całk. godz. pracy - Wartość')),
                ('b13_uwagi', models.TextField(blank=True)),
                ('b14_wartosc', models.CharField(blank=True, max_length=100, verbose_name='14. Licznik - całk. godz. pracy palnika - Wartość')),
                ('b14_uwagi', models.TextField(blank=True)),
                ('b15_wartosc', models.CharField(blank=True, max_length=100, verbose_name='15. Licznik - impulsy rozruchowe palnika - Wartość')),
                ('b15_uwagi', models.TextField(blank=True)),
                ('lab_godzina', models.TimeField(blank=True, null=True, verbose_name='Godzina przeprowadzenia analiz')),
                ('podpis_laboratorium', models.CharField(blank=True, max_length=200, verbose_name='Czytelny podpis (Laboratorium)')),
                ('wz_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Woda zasilająca - pH (25°C)')),
                ('wz_wapnioce_dh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Woda zasilająca - Wapniowce °dH')),
                ('wz_tlen_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Woda zasilająca - Tlen O₂ mg/litr')),
                ('wz_przewodnosc', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Woda zasilająca - Przewodność µS/cm')),
                ('wz_temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Woda zasilająca - Temperatura °C')),
                ('wz_wyglad', models.CharField(blank=True, choices=[('ok', 'Ok'), ('nie', 'Nie')], max_length=10, verbose_name='Woda zasilająca - Wygląd')),
                ('k_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kondensat - pH (25°C)')),
                ('k_wapnioce_dh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kondensat - Wapniowce °dH')),
                ('k_przewodnosc', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Kondensat - Przewodność µS/cm')),
                ('wk_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Woda kotłowa - pH (25°C)')),
                ('wk_wapnioce_dh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Woda kotłowa - Wapniowce °dH')),
                ('wk_przewodnosc', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Woda kotłowa - Przewodność µS/cm')),
                ('wk_wyglad', models.CharField(blank=True, choices=[('ok', 'Ok'), ('nie', 'Nie')], max_length=10, verbose_name='Woda kotłowa - Wygląd')),
                ('wu_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Woda po uzdatnianiu - pH (25°C)')),
                ('wu_wapnioce_dh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Woda po uzdatnianiu - Wapniowce °dH')),
                ('wu_przewodnosc', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Woda po uzdatnianiu - Przewodność µS/cm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laborant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_forms', to=settings.AUTH_USER_MODEL, verbose_name='Laborant')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_forms', to=settings.AUTH_USER_MODEL, verbose_name='Technik')),
            ],
            options={
                'verbose_name': 'Formularz nadzoru kotłowni',
                'verbose_name_plural': 'Formularze nadzoru kotłowni',
                'ordering': ['-data', '-godzina'],
            },
        ),
    ]
