# Generated by Django 6.0.5 on 2026-06-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotlownia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kotlowniaformularz',
            name='status',
            field=models.CharField(choices=[('techniczny', 'Etap 1 – Dział Techniczny'), ('laboratorium', 'Etap 2 – Laboratorium'), ('zakonczony', 'Zakończony')], default='techniczny', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='kotlowniaformularz',
            name='podpis_laboratorium',
            field=models.TextField(blank=True, verbose_name='Podpis cyfrowy (Laboratorium – base64)'),
        ),
        migrations.AlterField(
            model_name='kotlowniaformularz',
            name='podpis_techniczny',
            field=models.TextField(blank=True, verbose_name='Podpis cyfrowy (Dział Techniczny – base64)'),
        ),
    ]
