# Generated by Django 6.0.5 on 2026-06-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True, verbose_name='Nazwa klastra')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grupy', models.ManyToManyField(blank=True, to='auth.group', verbose_name='Role w klastrze')),
            ],
            options={
                'verbose_name': 'Klaster',
                'verbose_name_plural': 'Klastry',
                'ordering': ['nazwa'],
            },
        ),
    ]
