# Generated by Django 6.0.5 on 2026-09-16 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspekcjaPunkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField(verbose_name='Treść punktu')),
                ('kolejnosc', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Punkt kontrolny',
                'verbose_name_plural': 'Punkty kontrolne',
                'ordering': ['kolejnosc'],
            },
        ),
        migrations.CreateModel(
            name='InspekcjaSekcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_inspekcji', models.CharField(choices=[('wed', 'Inspekcja WED')], default='wed', max_length=20, verbose_name='Typ inspekcji')),
                ('nazwa', models.CharField(max_length=200, verbose_name='Nazwa sekcji')),
                ('kolejnosc', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Sekcja listy kontrolnej',
                'verbose_name_plural': 'Sekcje listy kontrolnej',
                'ordering': ['typ_inspekcji', 'kolejnosc'],
            },
        ),
        migrations.CreateModel(
            name='InspekcjaPodpunkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField(verbose_name='Treść podpunktu')),
                ('kolejnosc', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('punkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podpunkty', to='inspekcja.inspekcjapunkt')),
            ],
            options={
                'verbose_name': 'Podpunkt kontrolny',
                'verbose_name_plural': 'Podpunkty kontrolne',
                'ordering': ['kolejnosc'],
            },
        ),
        migrations.AddField(
            model_name='inspekcjapunkt',
            name='sekcja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punkty', to='inspekcja.inspekcjasekcja'),
        ),
        migrations.CreateModel(
            name='Zmiana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('typ', models.CharField(choices=[('ranna', 'Ranna (06:00–14:00)'), ('popoludniowa', 'Popołudniowa (14:00–22:00)'), ('nocna', 'Nocna (22:00–06:00)')], max_length=20, verbose_name='Typ zmiany')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('osoby', models.ManyToManyField(blank=True, related_name='zmiany', to=settings.AUTH_USER_MODEL, verbose_name='Osoby na zmianie')),
            ],
            options={
                'verbose_name': 'Zmiana',
                'verbose_name_plural': 'Zmiany',
                'ordering': ['-data', 'typ'],
                'unique_together': {('data', 'typ')},
            },
        ),
        migrations.CreateModel(
            name='Inspekcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('wed', 'Inspekcja WED')], default='wed', max_length=20, verbose_name='Typ inspekcji')),
                ('miejsce', models.CharField(blank=True, choices=[('warsztat_elektryk', 'Warsztat elektryków (przy śluzie)'), ('regal_dt_magazyn', 'Regał DT w Magazynie (niedaleko magazynku aromatów)'), ('warsztat', 'Warsztat'), ('kontener_chemia', 'Kontener - magazynek chemii'), ('kontener_czesci', 'Kontener - magazynek części zamiennych'), ('magazynek_elektronika', 'Magazynek elektroniki'), ('biuro_dt', 'Biuro DT (sprawdzenie dokumentacji)'), ('warsztat_rampa1', 'Warsztat przy rampie 1')], max_length=100, verbose_name='Miejsce inspekcji')),
                ('status', models.CharField(choices=[('w_toku', 'W toku'), ('zakonczona', 'Zakończona')], default='w_toku', max_length=20, verbose_name='Status')),
                ('ukryta', models.BooleanField(default=False, verbose_name='Ukryta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspekcje_utworzone', to=settings.AUTH_USER_MODEL)),
                ('osoby_kontrolujace', models.ManyToManyField(blank=True, related_name='inspekcje_kontrolowane', to=settings.AUTH_USER_MODEL, verbose_name='Osoby kontrolujące')),
                ('zmiana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspekcje', to='inspekcja.zmiana', verbose_name='Zmiana')),
            ],
            options={
                'verbose_name': 'Inspekcja',
                'verbose_name_plural': 'Inspekcje',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspekcjaWynik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wynik', models.CharField(choices=[('ok', 'OK'), ('nok', 'Niezgodne'), ('nd', 'Nie dotyczy')], default='nd', max_length=5)),
                ('uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='inspekcje/', verbose_name='Zdjęcie')),
                ('analiza_ai', models.TextField(blank=True, verbose_name='Analiza AI')),
                ('ai_sugestia', models.CharField(blank=True, max_length=400, verbose_name='Sugestia AI (sekcja)')),
                ('ai_pasuje', models.BooleanField(blank=True, null=True)),
                ('inspekcja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wyniki', to='inspekcja.inspekcja')),
                ('podpunkt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inspekcja.inspekcjapodpunkt')),
                ('punkt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inspekcja.inspekcjapunkt')),
                ('sekcja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspekcja.inspekcjasekcja')),
            ],
            options={
                'verbose_name': 'Wynik inspekcji',
                'verbose_name_plural': 'Wyniki inspekcji',
                'unique_together': {('inspekcja', 'punkt', 'podpunkt')},
            },
        ),
    ]
